name: Deploy Static Website

on:
  push:
    branches:
      - main
      - CFT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/s3-static-site.yaml \
            --stack-name static-website-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Upload Website Files
        run: |
          aws s3 sync website/ s3://devops-static-site-2026